# This is a basic workflow that is manually triggered

name: deploy-reduction-modules

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      job:
        # Description to be shown in the UI
        description: "Job Id"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - Select Job Id
          - deploy_reduction_module_1
          - deploy_reduction_module_2
          - deploy_reduction_module_3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  # reduction_module_1 deployment job
  deploy_reduction_module_1:
    name: reduction_module_1 deployment
    if: github.event.inputs.job == 'deploy_reduction_module_1'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Clone github-worflows repository to AWS EC2
        run: |
          if [ -d "./github-workflows" ]; then
            cd ./github-workflows
            git pull
          else
            git clone https://github.com/sriharsha219/github-workflows
          fi
      - name: Run reduction_module_1.py script in AWS EC2
        run: |
          cd ./github-workflows/reduction
          python3 reduction_module_1.py
  # reduction_module_2 deployment job
  deploy_reduction_module_2:
    name: reduction_module_2 deployment
    if: github.event.inputs.job == 'deploy_reduction_module_2'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Clone github-worflows repository to AWS EC2
        run: |
          if [ -d "./github-workflows" ]; then
            cd ./github-workflows
            git pull
          else
            git clone https://github.com/sriharsha219/github-workflows
          fi
      - name: Run reduction_module_2.py script in AWS EC2
        run: |
          cd ./github-workflows/reduction
          python3 reduction_module_2.py
  # reduction_module_3 deployment job
  deploy_reduction_module_3:
    name: reduction_module_3 deployment
    if: github.event.inputs.job == 'deploy_reduction_module_3'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runner's shell
      - name: Clone github-worflows repository to AWS EC2
        run: |
          if [ -d "./github-workflows" ]; then
            cd ./github-workflows
            git pull
          else
            git clone https://github.com/sriharsha219/github-workflows
          fi
      - name: Run reduction_module_3.py script in AWS EC2
        run: |
          cd ./github-workflows/reduction
          python3 reduction_module_3.py
